### ISSUE TITLE
Populate column_names in define_fields

### ISSUE THREAD

**Issue by ohaddahan** [Paxa/light_record#10]
https://github.com/Paxa/light_record/blob/490396eaf46ce60686d3a33f683b3395bd83c9e3/lib/light_record.rb#L160

Since `column_names` is a mapping of `@fields` and `@fields` is populated only in `define_fields`.

```
@fields ||= []
@column_names ||= []
fields.each do |field|
        @fields << field.to_sym
        @column_names << field.to_s
....
....
....

def column_names
  @column_names ||= []
end
```

**Comment by Paxa** [comment]
Thanks for all your comments, will fix it later.
For `column_names`, I think we can do `@@column_names ||= @fields.map(&:to_s)`
Because it create new class for each query

**Comment by ohaddahan** [comment]
Yes, if it's common on the entire class than this can save up some unneeded work, lazy is always good :)

**Comment by Paxa** [comment]
Fixed by https://github.com/Paxa/light_record/commit/68d9e6858eb0065a8bd80ee3cb6c36625a9d8cc5
