### ISSUE TITLE
write_attribute_without_type_cast, unneeded intermediate variable

### ISSUE THREAD

**Issue by ohaddahan** [Paxa/light_record#6]
https://github.com/Paxa/light_record/blob/490396eaf46ce60686d3a33f683b3395bd83c9e3/lib/light_record.rb#L105

The method:

```
def write_attribute_without_type_cast(attr_name, value)
          name = attr_name.to_sym
          @attributes[name] = value
        end
```

Can be rewritten as below, no need to an intermediate variable.

```
def write_attribute_without_type_cast(attr_name, value)
          @attributes[attr_name.to_sym] = value
        end
```

**Comment by Paxa** [comment]
Fixed by https://github.com/Paxa/light_record/commit/68d9e6858eb0065a8bd80ee3cb6c36625a9d8cc5
