### ISSUE TITLE
column_names memoization 

### ISSUE THREAD

**Issue by ohaddahan** [Paxa/light_record#7]
https://github.com/Paxa/light_record/blob/490396eaf46ce60686d3a33f683b3395bd83c9e3/lib/light_record.rb#L159

I assume column_names will always return the same.
No need to rerun map over and over.

```
    def column_names
      @fields.map(&:to_s)
    end
```

Consider:

```
    def column_names
      @column_names ||= @fields.map(&:to_s)
    end
```

**Comment by Paxa** [comment]
Fixed by https://github.com/Paxa/light_record/commit/68d9e6858eb0065a8bd80ee3cb6c36625a9d8cc5
