### ISSUE TITLE
Unneeded is_a? check.

### ISSUE THREAD

**Issue by ohaddahan** [Paxa/light_record#8]
https://github.com/Paxa/light_record/blob/490396eaf46ce60686d3a33f683b3395bd83c9e3/lib/light_record.rb#L134

`        field = field.to_sym unless field.is_a?(Symbol)`

This code will not run `to_sym` only if the object is already a `Symbol`.
Benchmarking `to_sym` and `is_a?` on a `Symbol` shows little difference (with slightly better performance to `some_symbol.to_sym`)
Hence can skip it and goes straight to `@fields << field`

```
require 'benchmark/ips'
foo = :foo
Benchmark.ips do |x|
  x.config(time: 3, warmup: 1)

  x.report("to_sym") do
    foo.to_sym
  end
  x.report("is_a?") do
    foo.is_a?(Symbol)
  end
  x.compare!
end
```

> 
> Warming up --------------------------------------
>               to_sym   260.510k i/100ms
>                is_a?   250.468k i/100ms
> Calculating -------------------------------------
>               to_sym      8.443M (± 9.9%) i/s -     25.009M in   3.003609s
>                is_a?      8.308M (± 8.8%) i/s -     24.796M in   3.025379s
> 
> Comparison:
>               to_sym:  8443024.9 i/s
>                is_a?:  8307715.1 i/s - same-ish: difference falls within error

**Comment by Paxa** [comment]
Fixed by https://github.com/Paxa/light_record/commit/68d9e6858eb0065a8bd80ee3cb6c36625a9d8cc5
