### ISSUE TITLE
Save one unneeded include?

### ISSUE THREAD

**Issue by ohaddahan** [Paxa/light_record#9]
https://github.com/Paxa/light_record/blob/490396eaf46ce60686d3a33f683b3395bd83c9e3/lib/light_record.rb#L147

`      if !fields.include?(:id) && !fields.include?("id") && primary_key.present?`

Change the check on `@fields` which get populated by `fields` just before this check.
`@fields` contains only symbols, hence `fields.include?("id")` can be deleted.

**Comment by Paxa** [comment]
Fixed by https://github.com/Paxa/light_record/commit/68d9e6858eb0065a8bd80ee3cb6c36625a9d8cc5
